## Numpy: Package for Multidimensional Array

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
list_of_lists=[[1,2,3], [4,5,6], [7,8,9]]
sample_matrix=np.array(list_of_lists)

In [4]:
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [7]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [10]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [13]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.rand(3,2)

array([[0.82342425, 0.68664069],
       [0.72000191, 0.62747874],
       [0.47078193, 0.12863458]])

In [19]:
np.random.randn(3,2)  #in randn the last n is for negative

array([[-0.10026378,  1.21027882],
       [ 0.58482971, -1.99801512],
       [-0.41710234, -0.9949769 ]])

In [20]:
np.random.randint(1,5)

1

In [21]:
np.random.randint(34,100,50)

array([47, 45, 91, 65, 46, 49, 72, 67, 55, 70, 45, 86, 57, 53, 77, 86, 52,
       88, 84, 54, 54, 94, 83, 43, 40, 46, 70, 52, 65, 83, 41, 42, 68, 59,
       85, 44, 57, 51, 35, 41, 91, 58, 85, 87, 40, 41, 51, 39, 38, 42])

In [22]:
sample_array = np.arange(30)

In [23]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
rand_array=np.random.randint(0,100,20)
rand_array

array([ 9, 58, 85, 31, 14,  9, 65, 72, 15, 48, 48, 63, 53, 98, 44, 36, 12,
       43, 88, 87])

In [25]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [26]:
rand_array.min()

9

In [27]:
rand_array.argmin()   # arg - index if minimum value 

0

In [28]:
a=np.eye(5)

In [29]:
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
sample_array = np.arange(10,21)

In [32]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
sample_array[3]

13

In [34]:
sample_array[3:7]

array([13, 14, 15, 16])

In [35]:
sample_array[1:4]=100

In [36]:
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [37]:
sample_array = np.arange(10,21)

In [38]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
sample_array [0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [40]:
subset_sample_array = sample_array[0:7]

In [41]:
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [42]:
subset_sample_array[1:4]=1001

In [43]:
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [44]:
subset_sample_array[:]=1001

In [45]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional Array

In [46]:
sample_matrix = np.array([[50,20,1,23],[24,23,21,33],[56,76,24,76]])

In [47]:
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24, 76]])

In [48]:
sample_matrix[0:2,2]

array([ 1, 21])

In [49]:
sample_matrix[2,:]

array([56, 76, 24, 76])

In [50]:
sample_matrix[2]

array([56, 76, 24, 76])

In [51]:
sample_matrix[:, (1,2,0)]

array([[20,  1, 50],
       [23, 21, 24],
       [76, 24, 56]])

In [52]:
sample_matrix[:,3]

array([23, 33, 76])

In [53]:
sample_array=np.arange(1,20)

In [54]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [55]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [56]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [57]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [58]:
np.std(sample_array)

5.477225575051661

In [59]:
np.max(sample_array)

19

In [60]:
np.min(sample_array)

1

In [61]:
np.argmax(sample_array)

18

In [62]:
np.argmin(sample_array)

0

In [63]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [64]:
np.std(sample_array)

5.477225575051661

In [65]:
np.var(sample_array)

30.0

In [66]:
np.mean(sample_array)

10.0

In [67]:
array = np.random.randn(3,4)

In [68]:
array

array([[-0.77906454,  0.16664022,  0.24999346, -0.05479946],
       [-0.72120736, -1.18235367,  3.08201118, -1.42473278],
       [-0.68089679,  0.28652447, -0.45939645,  1.73480884]])

In [69]:
np.round(array,decimals=3)

array([[-0.779,  0.167,  0.25 , -0.055],
       [-0.721, -1.182,  3.082, -1.425],
       [-0.681,  0.287, -0.459,  1.735]])

In [70]:
sports = np.array(['Golf', 'Cricket', 'Football', 'Cricket', 'Football', 'Basketball'])

In [71]:
np.unique(sports)

array(['Basketball', 'Cricket', 'Football', 'Golf'], dtype='<U10')